services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=tattle
      - POSTGRES_PASSWORD=weak_password
      - POSTGRES_DB=viral_spiral_dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ~/data/viral-spiral/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db_gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localhost
    volumes:
      - ./priv/localstack:/etc/localstack/init/ready.d
      - ~/data/viral-spiral/localstack:/var/lib/localstack
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4566/_localstack/health | grep '\"s3\": \"running\"'"]
      interval: 5s
      timeout: 5s
      retries: 10
